repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--explicit-package-bases"]
        exclude: ^(examples/|src/sample_app/)
        additional_dependencies: [types-aiofiles>=25.0.0]
