name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Rust toolchain (needed if ruff must be built from source)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Try to pre-install ruff (prefer binary wheel) so resolver won't fail
          python -m pip install "ruff>=0.16.0" --prefer-binary --index-url https://pypi.org/simple || true
          # Install project including dev extras (linters may already be present)
          python -m pip install -e '.[dev]' --index-url https://pypi.org/simple
      - name: Run linters and type checks
        run: |
          # Ruff for linting
          python -m ruff check .
          # Black check
          python -m black --check .
          # Mypy type check
          python -m mypy src
      - name: Run tests
        run: |
          python -m pytest -q
