name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run linters and type checks
        run: |
          # Ruff for linting
          python -m ruff check .
          # Black check
          python -m black --check .
          # Mypy type check
          python -m mypy src
      - name: Run tests
        run: |
          python -m pytest -q
